In [9]:
import numpy as np

print(np.__version__)

1.24.2


In [6]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
import numpy as pn
arr = pn.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
import numpy as an
arr = an.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 5 element on 2nd row: ', arr[1, 4])


print 5 element on 2nd row:  10


In [11]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 20

print(x)
print(arr)

[1 2 3 4 5]
[20  2  3  4  5]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 20

print(arr)
print(x)

[20  2  3  4  5]
[20  2  3  4  5]


In [14]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
