In [4]:
import numpy as np

arr = np.array([[1, 2, 3 ,4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4 ,5 , 6 ,7], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4 5 6 7]]]]]
shape of array : (1, 1, 1, 1, 7)


In [25]:
arr = np.array([1, 2, 3, 4 ,5 , 6 ,7,8,9,10,11,12])
new = arr.reshape(4,3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
